export const statusColor: Record<string, string> = {
  REQUESTED: 'yellow',
  SHELTER_DECLINED: 'red',
  PAYMENT_PENDING: 'blue',
  PAYMENT_EXPIRED: 'red',
  RENTER_DECLINED: 'red',
  SHELTER_WITHDREW: 'red',
  PAID: 'green',
  DISPUTE: 'orange',
  PEACEFULLY_TERMINATED: 'gray',
  DISPUTE_IN_FAVOR_OF_SHELTER: 'green',
  DISPUTE_IN_FAVOR_OF_RENTER: 'red',
  SHELTER_CANCELLED: 'red',
  RENTER_CANCELLED: 'gray',
};

export const statusLabel: Record<string, string> = {
  REQUESTED: 'Requested',
  SHELTER_DECLINED: 'Declined by shelter',
  PAYMENT_PENDING: 'Awaiting payment',
  PAYMENT_EXPIRED: 'Payment expired',
  RENTER_DECLINED: 'Declined by renter',
  SHELTER_WITHDREW: 'Shelter withdrew',
  PAID: 'Paid',
  DISPUTE: 'In dispute',
  PEACEFULLY_TERMINATED: 'Completed',
  DISPUTE_IN_FAVOR_OF_SHELTER: 'Dispute: shelter won',
  DISPUTE_IN_FAVOR_OF_RENTER: 'Dispute: renter won',
  SHELTER_CANCELLED: 'Cancelled by shelter',
  RENTER_CANCELLED: 'Cancelled by renter',
};

export const statusDescriptionRenter: Record<string, string> = {
  REQUESTED: 'Waiting for the shelter to review your request. No payment has been taken.',
  SHELTER_DECLINED: 'The shelter declined your rental request. No payment was taken.',
  PAYMENT_PENDING: 'The shelter has proposed rental terms. Review and pay to confirm.',
  PAYMENT_EXPIRED: 'You did not pay before the rental start date. The rental was cancelled and no payment was taken.',
  RENTER_DECLINED: 'You declined the shelter\'s proposed terms. No payment was taken.',
  SHELTER_WITHDREW: 'The shelter withdrew their proposed terms before you paid. No payment was taken.',
  PAID: 'You have paid for this rental. Your payment is held securely and will be released to the shelter 24 hours after the rental ends.',
  DISPUTE: 'You have raised a dispute. Your payment is on hold while an admin reviews the case.',
  PEACEFULLY_TERMINATED: 'The rental ended with no disputes. Payment has been released to the shelter.',
  DISPUTE_IN_FAVOR_OF_SHELTER: 'The dispute was resolved in favor of the shelter. Your payment was released to them.',
  DISPUTE_IN_FAVOR_OF_RENTER: 'The dispute was resolved in your favor. You have been refunded.',
  SHELTER_CANCELLED: 'The shelter cancelled this rental after you paid. You have been fully refunded.',
  RENTER_CANCELLED: 'You cancelled your request before the shelter responded. No payment was taken.',
};

export const statusDescriptionShelter: Record<string, string> = {
  REQUESTED: 'A renter has requested to rent this pet. No payment involved yet.',
  SHELTER_DECLINED: 'You declined this rental request. No payment was involved.',
  PAYMENT_PENDING: 'Terms proposed — waiting for the renter to pay. Do not hand over the pet yet. You can still withdraw.',
  PAYMENT_EXPIRED: 'The renter did not pay before the rental start date. The rental was cancelled and no payment was taken.',
  RENTER_DECLINED: 'The renter declined your proposed terms. No payment was taken.',
  SHELTER_WITHDREW: 'You withdrew your proposed terms before the renter paid. No payment was taken.',
  PAID: 'The renter has paid. You may now hand over the pet. Payment will be released to you 24 hours after the rental ends, provided no dispute is raised.',
  DISPUTE: 'The renter has raised a dispute. Your payout is on hold while an admin reviews the case.',
  PEACEFULLY_TERMINATED: 'The rental ended with no disputes. Payment has been released to you.',
  DISPUTE_IN_FAVOR_OF_SHELTER: 'The dispute was resolved in your favor. Payment has been released to you.',
  DISPUTE_IN_FAVOR_OF_RENTER: 'The dispute was resolved in favor of the renter. They have been refunded.',
  SHELTER_CANCELLED: 'You cancelled this rental after the renter paid. They have been fully refunded and you received nothing.',
  RENTER_CANCELLED: 'The renter cancelled their request before you responded. No payment was involved.',
};
